name: jlite-kernels-multi
channels:
  - conda-forge
dependencies:
  - jupyter_server
  - nodejs=20
  - pip:
    - jupyterlite-core>=0.6.0a10
    - jupyterlite-xeus>=4.0.0a7
    - jupyterlite-pyodide-kernel>=0.6.0a6
